mingw64: update to 5.0.2
Use the latest mingw64 release to get access to the latest Windows APIs

BUILDSDK_CPPFLAGS was emptied from poky.conf, but it's needed for mingw
build to include correct float.h. (error: '_MCW_DN' undeclared here)

Disable shared library for nativesdk-gettext as it fails with
'undefined reference to `xmlFree''

Change-Id: Ie2ffa6cccd6a1d378d720a8f9c5a79ed74eccd4f
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>